apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webapi-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      containers:
        - name: sample-webapi-container
          image: sample-webapi:dev-v1
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "700Mi"
              cpu: "400m"
          # envFrom:
          #   - configMapRef:
          #       name: mykustom-map-dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: sample-webapi-secret
