bases:
- ../../base

namespace: dev

patches:
- ./patches/replicas.yml
- ./patches/rolloutStrategy.yml
- ./patches/imageRef.yml
#- ./patches/probes.yml
- ./patches/resourceLimit.yml
#- ./patches/hostAliases.yml

configMapGenerator:
- name: mykustom-map-dev
  env: config.properties