apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  bases:  
  - ../../base

  namespace: dev

# resources:
# - deployment.yml
# - service.yml

# namePrefix: kustomapp-
# nameSuffix: -dev-v1

  patches:
#- ./patches/replicas.yml
#- ./patches/rolloutStrategy.yml
  - ./patches/imageRef.yml
#- ./patches/probes.yml
#- ./patches/resourceLimit.yml
#- ./patches/hostAliases.yml

# configMapGenerator:
# - name: mykustom-map-dev
#   env: config.properties