kind: Service
apiVersion: v1
metadata:
  name: sample-webapi-service
  namespace: dev
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP